### ISSUE TITLE
[BUG] Camera crashes when zoom on video

### ISSUE THREAD

**Issue by InvisibleKiller** [LeeXDA21/UnboundHub#1]
**Describe the bug**
Every time im in the camera, specifically using video, any time i try to zoom, the entire phone crashes and reboots.

**To Reproduce**
1. Go to Camera
2. Click on Video
3. Tap on any zoom
4. Phone crashes and reboots

**Expected behavior**
The video camera should zoom in on the shot.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Galaxy S20 Ultra 5G
 - Model: G988B
[log_e.log](https://github.com/LeeXDA21/UnboundHub/files/8476166/log_e.log)

**Additional context**
Log added using logkit as directed.

**Comment by LeeXDA21** [comment]
@InvisibleKiller Hi, I have just attempted to reproduce your bug and have been able to on my own device so I can now properly debug this issue. Thank you for the report.

**Comment by LeeXDA21** [comment]
This has been fixed in a future update.
