### ISSUE TITLE
[Bug]: Refresh rate setting crashes UC app

### ISSUE THREAD

**Issue by tommyhechtel** [LeeXDA21/UnboundHub#10]
### What is your Telegram Username?

@hans_olo

### Device

SM-G985F (Galaxy S20+ 4G)

### ROM Variant

UnboundROM

### Bug Description

When changing the screen refresh rate in Unbound Control app it crashes immediately. Also the "adaptive" setting is grayed out and cannot be selected. The screen resolution can be changed in the Unbound Control app, but no effect to actual setting in Samsung options menu.

### Bug Visual Description

https://drive.google.com/file/d/1FF357-p4V5WByzza38ci3FMAFcNFkNsZ/view?usp=drivesdk

### Log File(s)

https://drive.google.com/file/d/1ecCDupQmUbW3rl0OnjmE8GTm7ZcmmGwF/view?usp=drivesdk

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in a rom maintained by The Unbeyond Team and NOT present in any other ROM.
- [X] You understand and declare that if any information provided here is incorrect or instructions have not been followed correctly that it can lead to you being permanently banned from all Unbeyond owned servers.

**Comment by LeeXDA21** [comment]
The issue has been addressed; thank you for reading and taking the time to complete an ethical issue.
