### ISSUE TITLE
[Bug]: Media volume always at max

### ISSUE THREAD

**Issue by tommyhechtel** [LeeXDA21/UnboundHub#11]
### What is your Telegram Username?

@hans_olo

### Device

SM-G985F (Galaxy S20+ 4G)

### ROM Variant

UnboundROM

### Bug Description

The media volume cannot be adjusted. It is muted at 0%, but at maximum when slightly increased. The media volume bar is showing all single increase steps, but the speakers are at max volume all the time. This effect was directly after clean install of Unbound 2.3 when no apps or modules were installed.

### Bug Visual Description

https://drive.google.com/file/d/11G6DshiOzWN_0XeZpTaXDpqPYXzFGgZ4/view?usp=drivesdk

### Log File(s)

https://drive.google.com/file/d/138DiEkvaS6VYDy-Bm4_5TEjdPd8J8POI/view?usp=drivesdk

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in a rom maintained by The Unbeyond Team and NOT present in any other ROM.
- [X] You understand and declare that if any information provided here is incorrect or instructions have not been followed correctly that it can lead to you being permanently banned from all Unbeyond owned servers.

**Comment by LeeXDA21** [comment]
[VolumeFix_G98X.zip](https://github.com/LeeXDA21/TheUnbeyondHub/files/10785945/VolumeFix_G98X.zip)

@tommyhechtel Hello, please try this zip to fix the high volume.

**Comment by tommyhechtel** [comment]
Rc5 mod zip solved the issue
