### ISSUE TITLE
[Bug]: Camera Panorama

### ISSUE THREAD

**Issue by fefe-adrien** [LeeXDA21/UnboundHub#13]
### What is your Telegram Username?

fefe

### Device

SM-G985F (Galaxy S20+ 4G)

### ROM Variant

UnboundROM

### Bug Description

When I use Panorama mode in camera, the image of the camera is stucked, even if I change mode.
If I close the app, and start again, other mods are working, but not Panorama one.

### Bug Visual Description

[Video of the screen](https://drive.google.com/file/d/10IV8-_tldjXEX67BVWD6KTTDL_F6io0H/view?usp=sharing)

### Log File(s)

- [Logcat file](https://drive.google.com/file/d/10GtTn776Pwi5zXNI4x2XDexsMtLSK_Or/view?usp=sharing)

- [Log-all from UnboundControl App](https://drive.google.com/file/d/10GtTn776Pwi5zXNI4x2XDexsMtLSK_Or/view?usp=sharing)

### Additional checks

- [x] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in a rom maintained by The Unbeyond Team and NOT present in any other ROM.
- [X] You understand and declare that if any information provided here is incorrect or instructions have not been followed correctly that it can lead to you being permanently banned from all Unbeyond owned servers.

**Comment by LeeXDA21** [comment]
@fefe-adrien Ok, I will take a further look into this. I've not been able to replicate this bug on my side so it may be specific to G985F.

**Comment by LeeXDA21** [comment]
[PanoramaFix_G98X_rc1.zip](https://github.com/LeeXDA21/TheUnbeyondHub/files/10825969/PanoramaFix_G98X_rc1.zip)
@fefe-adrien Please try this fix.

**Comment by LeeXDA21** [comment]
Tested externally, marked as fixed.
