### ISSUE TITLE
[Bug]: Snapchat shows cannot open camera error

### ISSUE THREAD

**Issue by carlkevin** [LeeXDA21/UnboundHub#15]
### What is your Telegram Username?

@carlkevin11

### Device

SM-G980F (Galaxy S20 4G)

### ROM Variant

UnboundROM

### Bug Description

When i open Snapchat, it shows an error that it cannot open the camera. I cleared the app data and it worked. I close and open the app and the error is back. 

### Bug Visual Description

https://drive.google.com/file/d/12y5hIheQ28tvvYNPGag_dSPxs_e1DetK/view?usp=drivesdk

### Log File(s)

N/A

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in a rom maintained by The Unbeyond Team and NOT present in any other ROM.
- [X] You understand and declare that if any information provided here is incorrect or instructions have not been followed correctly that it can lead to you being permanently banned from all Unbeyond owned servers.

**Comment by LeeXDA21** [comment]
@carlkevin You have failed to provide a log, issue closed due to lack of information.
