### ISSUE TITLE
[BUG] 120 Hz on adaptive mode

### ISSUE THREAD

**Issue by zidane5252** [LeeXDA21/UnboundHub#2]
**Describe the bug**
The 120 hz refresh rate is not working. Just working through galaxy max hz app.

**To Reproduce**

**Expected behavior**
Adaptive mode could work as the high 120 hz refresh rate changing this setting on the one ui settings menu.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [Galaxy S20 plus LTE]
 - Model: [G985F]

**Additional context**
- Gather logs by using [LoggingKit_v5](https://github.com/LeeXDA21/UnboundHub/releases/download/v5.0/LoggingKit_v5.zip) when applicable

**Comment by LeeXDA21** [comment]
No log provided, template not followed.
