### ISSUE TITLE
3bminit batery

### ISSUE THREAD

**Issue by ayhanornek1971** [LeeXDA21/UnboundHub#3]
Can you make the 3 minute battery application as a mod package, please.thanks

**Comment by LeeXDA21** [comment]
@ayhanornek1971 A rom control is in development, due to this the issue will be closed and marked as an enhancement.

**Comment by ayhanornek1971** [comment]
Ok thanks

21 May 2022 Cmt 21:41 tarihinde LeeXDA18 ***@***.***> şunu
yazdı:
