### ISSUE TITLE
Brightness too low 

### ISSUE THREAD

**Issue by grantious** [LeeXDA21/UnboundHub#4]
Ever since I flashed the 1.2 rom on my G988B device the brightness has been extremely low, I noticed at first I flashed a setting like that when I first did it but I reflashed your rom without the brightness setting checked and it's still extremely low.... I've turned it up to max and I've unchecked the extra dim feature.

I read during development something like this was an issue, I was wondering if there's any way of fixing it without doing clean flash because I'm so over doing that 🤣 I tried looking for a solution myself but all I could find was gravity box but that doesn't work on a12 unfortunately

**Comment by LeeXDA21** [comment]
@grantious Hi, I use G988B as a testing device for the ROM before each release and currently do not seem to have this issue as it was fixed since V1.0, could you provide a log?

**Comment by Stezzza** [comment]
Just wanted to say that I am also experiencing this issue. It was for this sole reason that I had to switch to BeyondROM, if you do fix it I will go back to Unbound! <3

**Comment by Stezzza** [comment]
Find out that this is only an issue if you select "Keep stock blur" during the setup...
