### ISSUE TITLE
camera fail G985F

### ISSUE THREAD

**Issue by Sheppel** [LeeXDA21/UnboundHub#5]
**Describe the bug**
black camera output, camera fails

**To Reproduce**
1. Go to "Camera App"
2. Error shown

**Expected behavior**
Camera supposedly to output image

**Screenshots**
![Screenshot_20220717-081224_Camera](https://user-images.githubusercontent.com/109443458/179375895-eac3b593-2e8f-48f7-8385-f9f185acbeaa.jpg)

**Smartphone (please complete the following information):**
 - Device: [S20+ 4G]
 - Model: [G985F]

**Additional context**
- [camera fail.log](https://github.com/LeeXDA21/UnboundHub/files/9126826/camera.fail.log)

**Comment by telmob** [comment]
Same exact thing happens on SM-G980F (Galaxy S20 4G)
Full wipe install with recommended firmware version G980FXXSEFVE6.
[log_All.zip](https://github.com/LeeXDA21/UnboundHub/files/9128294/log_All.zip)
I'll install Unbound 1.2 and see if a dirty flash also displays this issue.
