### ISSUE TITLE
[Bug]: Unbound Control crash

### ISSUE THREAD

**Issue by tommyhechtel** [LeeXDA21/UnboundHub#9]
### What is your Telegram Username?

@hans_olo

### Device

SM-G985F (Galaxy S20+ 4G)

### ROM Variant

UnboundROM

### Bug Description

Since update of Unbound Control in Playstore on 20. Feb 2023 the app is immediately crashing directly after start. Logcat attached. Unbound ROM 2.3

### Bug Visual Description

https://drive.google.com/file/d/1mnzx_bGNcv7Y6ayVoAs-yHl3-VsaLnLO/view?usp=drivesdk

### Log File(s)

https://drive.google.com/file/d/14XG4DeILg-wA6FQjeRxnxGisC-izqYh0/view?usp=drivesdk

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in a rom maintained by The Unbeyond Team and NOT present in any other ROM.
- [X] You understand and declare that if any information provided here is incorrect or instructions have not been followed correctly that it can lead to you being permanently banned from all Unbeyond owned servers.

**Comment by LeeXDA21** [comment]
@tommyhechtel Hi, I can see the issue, I will publish an update to the app shortly.

**Comment by LeeXDA21** [comment]
Issue has been addressed, thank you for actually reading and taking time to fill out a proper issue.
